### PR TITLE
prep: 3話フレーム

### PR DESCRIPTION
**Pull request by fearocanity**
3rd episode.

### CODE REVIEW

**Comment by fearocanity** [comment]
@Rendevior I think i'm done for now. Push if lgty.. 👍 ありがとう。。

**Comment by Rendevior** [comment]
> @Rendevior I think i'm done for now. Push if lgty.. 👍 ありがとう。。

Got it. I'm gonna improve the error handlings for it.

**Comment by Rendevior** [comment]
This is it, i guess... I don't have many to add lol.
And also i noticed that we switched to `3.5` fps, should we finalize it to `3.5`?

**Comment by fearocanity** [comment]
> This is it, i guess... I don't have many to add lol. And also i noticed that we switched to `3.5` fps, should we finalize it to `3.5`?

Sure.

**Review by Rendevior — APPROVED** [review]
Already Tested it earlier. :>

**Comment by Rendevior** [comment]
We might as well upload those frames in Releases tab on GDrive/Mega, This repo is getting bigger and bigger in size lol, I guess i'm gonna do it. I have a decent upload speeds and also bought beefy PC.

**Pull request merged**
